"""remove user id in file

Revision ID: 5b85f84ab0d8
Revises: dc9b1144c833
Create Date: 2025-06-02 23:13:25.591129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b85f84ab0d8'
down_revision: Union[str, None] = 'dc9b1144c833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
