"""Change file_path to base_url and s3_key

Revision ID: 7afc301b2dce
Revises: ea96ce3c9b6e
Create Date: 2025-04-08 20:51:37.315407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7afc301b2dce'
down_revision: Union[str, None] = 'ea96ce3c9b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('base_url', sa.String(length=255), nullable=False))
    op.add_column('files', sa.Column('s3_key', sa.String(length=255), nullable=False))
    op.drop_column('files', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_path', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('files', 's3_key')
    op.drop_column('files', 'base_url')
    # ### end Alembic commands ###
