"""add width and height columns to files table

Revision ID: 8ee0ea1f1910
Revises: a7a9cfcd98a5
Create Date: 2025-04-19 12:01:18.019558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee0ea1f1910'
down_revision: Union[str, None] = 'a7a9cfcd98a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'height')
    op.drop_column('files', 'width')
    # ### end Alembic commands ###
