"""remove user_id from verify model

Revision ID: 9eb8d54f9a9b
Revises: e0b32fa55e63
Create Date: 2025-04-01 11:01:32.480823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9eb8d54f9a9b'
down_revision: Union[str, None] = 'e0b32fa55e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('verifies_ibfk_1', 'verifies', type_='foreignkey')
    op.drop_column('verifies', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifies', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('verifies_ibfk_1', 'verifies', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
