"""rename file_type to content_type

Revision ID: a7a9cfcd98a5
Revises: a83cb88b9d55
Create Date: 2025-04-19 11:55:55.578108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a7a9cfcd98a5'
down_revision: Union[str, None] = 'a83cb88b9d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('content_type', sa.String(length=100), nullable=False))
    op.drop_column('files', 'file_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_type', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('files', 'content_type')
    # ### end Alembic commands ###
