"""add user table

Revision ID: c10dceb44fb3
Revises: 9eb8d54f9a9b
Create Date: 2025-04-05 13:58:27.271997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c10dceb44fb3'
down_revision: Union[str, None] = '9eb8d54f9a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('terms_of_service', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('privacy_policy', sa.Boolean(), nullable=False))
    op.drop_index('ix_users_username', table_name='users')
    op.create_unique_constraint(None, 'users', ['nickname'])
    op.drop_column('users', 'username')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('full_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_column('users', 'privacy_policy')
    op.drop_column('users', 'terms_of_service')
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
