"""add s3_key_thumbnail column to files table

Revision ID: e3a3ee57d6cc
Revises: af36b695aff7
Create Date: 2025-04-26 15:45:00.412790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3a3ee57d6cc'
down_revision: Union[str, None] = 'af36b695aff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('s3_key_thumbnail', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 's3_key_thumbnail')
    # ### end Alembic commands ###
