name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Package application
      run: |
         tar --exclude=".git" \
          --exclude=".github" \
          --exclude="__pycache__" \
          --exclude="*.pyc" \
          --exclude="venv" \
          --exclude=".gitignore" \
          --exclude=".python-version" \
          --exclude=".cursorrules" \
          --exclude="README.md" \
          --exclude="app/__pycache__" \
          --exclude="src/__pycache__" \
          -czvf app.tar.gz \
          main.py app/ requirements.txt alembic/ alembic.ini

    - name: Copy package to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "app.tar.gz"
        target: "/home/ec2-user/"

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user
          rm -rf app || true
          mkdir app
          tar -xzvf app.tar.gz -C app
          cd app
          source venv/bin/activate || python3 -m venv venv && source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          # 예: uvicorn 실행
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 & 